version = 0.1
[default.deploy.parameters]
stack_name = "sam-nestjs-lambda"
resolve_s3 = true
s3_prefix = "sam-nestjs-lambda"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["NestjsFunction=151268123722.dkr.ecr.ap-northeast-1.amazonaws.com/samnestjslambdaed30537b/nestjsfunction81005fefrepo"]
