AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-nestjs-lambda

  Sample SAM Template for sam-nestjs-lambda

Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  NestjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Architectures:
      - arm64
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile